name: Parallal fina run

on: push  # Run on every push

jobs:
  Add-To-Cart-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:addToCart


  Reg-Flow-run:
     runs-on: ubuntu-22.04
     steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
         command: npm run test:registerFlow

